package com.dnd.Exercise.domain.sports.entity;

public enum Sports {
    AmericanFootball(8),
    Archery(4.3),
    AustralianFootball(8),
    Badminton(5.5),
    Baseball(5),
    Basketball(6.5),
    Bowling(3.8),
    Boxing(7.8),
    Climbing(8),
    Cricket(4.8),
    CrossTraining(6),
    Curling(4),
    Cycling(5.7),
    Dance(3),
    Elliptical(5),
    EquestrianSports(5.5),
    Fencing(6),
    Fishing(3.5),
    FunctionalStrengthTraining(6),
    Golf(4.8),
    Gymnastics(3.8),
    Handball(12),
    Hiking(7),
    Hockey(8),
    Hunting(5),
    Lacrosse(8),
    MartialArts(5.3),
    MindAndBody(1),
    PaddleSports(4),
    Play(2.2),
    PreparationAndRecovery(3.5),
    Racquetball(7),
    Rowing(4.8),
    Rugby(10),
    Running(7),
    Sailing(3),
    SkatingSports(7),
    SnowSports(7),
    Soccer(7),
    Softball(5),
    Squash(7.3),
    StairClimbing(4),
    SurfingSports(3),
    Swimming(8),
    TableTennis(4),
    Tennis(7),
    TrackAndField(4),
    TraditionalStrengthTraining(6),
    Volleyball(4),
    Walking(3.8),
    WaterFitness(7.3),
    WaterPolo(10),
    WaterSports(6),
    Wrestling(6),
    Yoga(3),
    Barre(3),
    CoreTraining(8),
    CrossCountrySkiing(13.3),
    DownhillSkiing(5.3),
    Flexibility(2.3),
    HighIntensityIntervalTraining(8),
    JumpRope(8.8),
    Kickboxing(10.3),
    Pilates(3),
    Snowboarding(4.3),
    Stairs(8.3),
    StepTraining(8.5),
    WheelchairWalkPace(3.5),
    WheelchairRunPace(8),
    TaiChi(3),
    MixedCardio(6),
    HandCycling(10);

    private double met;

    Sports(double met) {
        this.met = met;
    }

    public double getMet() {
        return met;
    }
}
